services:
  mongo:
    image: "mongo"
    ports:
      - "${MONGOPORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGOUSER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGOPASS}"
  redis:
    image: "redis:7.2.0-alpine3.18"
    ports: 
      - "6379:6379"